
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint;
import org.datacontract.schemas._2004._07.openglovewcf.ArrayOfGlove;
import org.datacontract.schemas._2004._07.openglovewcf.Glove;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOGService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.openglovewcf.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IOGService {


    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.openglovewcf.ArrayOfGlove
     */
    @WebMethod(operationName = "GetGloves", action = "http://tempuri.org/IOGService/GetGloves")
    @WebResult(name = "GetGlovesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetGloves", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGloves")
    @ResponseWrapper(localName = "GetGlovesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGlovesResponse")
    public ArrayOfGlove getGloves();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.openglovewcf.ArrayOfGlove
     */
    @WebMethod(operationName = "RefreshGloves", action = "http://tempuri.org/IOGService/RefreshGloves")
    @WebResult(name = "RefreshGlovesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RefreshGloves", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RefreshGloves")
    @ResponseWrapper(localName = "RefreshGlovesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RefreshGlovesResponse")
    public ArrayOfGlove refreshGloves();

    /**
     * 
     * @param glove
     */
    @WebMethod(operationName = "SaveGlove", action = "http://tempuri.org/IOGService/SaveGlove")
    @RequestWrapper(localName = "SaveGlove", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveGlove")
    @ResponseWrapper(localName = "SaveGloveResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveGloveResponse")
    public void saveGlove(
        @WebParam(name = "glove", targetNamespace = "http://tempuri.org/")
        Glove glove);

    /**
     * 
     * @param intensity
     * @param actuator
     * @param gloveAddress
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Activate", action = "http://tempuri.org/IOGService/Activate")
    @WebResult(name = "ActivateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Activate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Activate")
    @ResponseWrapper(localName = "ActivateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActivateResponse")
    public Integer activate(
        @WebParam(name = "gloveAddress", targetNamespace = "http://tempuri.org/")
        String gloveAddress,
        @WebParam(name = "actuator", targetNamespace = "http://tempuri.org/")
        Integer actuator,
        @WebParam(name = "intensity", targetNamespace = "http://tempuri.org/")
        Integer intensity);

    /**
     * 
     * @param gloveAddress
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Connect", action = "http://tempuri.org/IOGService/Connect")
    @WebResult(name = "ConnectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Connect", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Connect")
    @ResponseWrapper(localName = "ConnectResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConnectResponse")
    public Integer connect(
        @WebParam(name = "gloveAddress", targetNamespace = "http://tempuri.org/")
        String gloveAddress);

    /**
     * 
     * @param gloveAddress
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Disconnect", action = "http://tempuri.org/IOGService/Disconnect")
    @WebResult(name = "DisconnectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Disconnect", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Disconnect")
    @ResponseWrapper(localName = "DisconnectResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DisconnectResponse")
    public Integer disconnect(
        @WebParam(name = "gloveAddress", targetNamespace = "http://tempuri.org/")
        String gloveAddress);

    /**
     * 
     * @param actuators
     * @param gloveAddress
     * @param intensityList
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "ActivateMany", action = "http://tempuri.org/IOGService/ActivateMany")
    @WebResult(name = "ActivateManyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActivateMany", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActivateMany")
    @ResponseWrapper(localName = "ActivateManyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActivateManyResponse")
    public Integer activateMany(
        @WebParam(name = "gloveAddress", targetNamespace = "http://tempuri.org/")
        String gloveAddress,
        @WebParam(name = "actuators", targetNamespace = "http://tempuri.org/")
        ArrayOfint actuators,
        @WebParam(name = "intensityList", targetNamespace = "http://tempuri.org/")
        ArrayOfint intensityList);

}
